version: '3.1'

services:
  analytics:
    image: repo.treescale.com/infinions/analytics:v1.0.2
    environment:
      API_PORT: 5600
      DB_NAME: infin_dev
      DB_USER: infin
      DB_PORT: 5432
      DB_PWD: infin
      DB_HOST: db
      DB_ANALYTICS: 'mongodb://analytics_db:27017/'
      DB_ANALYTICS_HOST: analytics_db
      DB_ANALYTICS_PORT: 27017
    ports:
    - 5600:5600
    restart: always

  analytics_db:
    image: mongo
    ports:
    - 27017:27017
    restart: always

  pt-invoices:
    image: repo.treescale.com/infinions/pt-invoices:v1.0.0
    environment:
      NODE_PORT: 3000
      NODE_ENV: production
    ports:
    - 3000:3000
    restart: always

  db:
    image: postgres
    environment:
      POSTGRES_DB: infin_dev
      POSTGRES_PASSWORD: infin
      POSTGRES_USER: infin
    ports:
    - 5432:5432
    restart: always
