version: '3.1'

services:
  analytics:
    image: repo.treescale.com/infinions/analytics:v1.0.0
    environment:
      API_PORT: 5000
      DB_NAME: infin_dev
      DB_USER: infin
      DB_PORT: 5432
      DB_PWD: infin
      DB_HOST: db
    ports:
    - 5600:5600

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: infin_dev
      POSTGRES_PASSWORD: infin
      POSTGRES_USER: infin
    ports:
    - 5432:5432
