version: '3.1'

services:
  analytics:	
    image: repo.treescale.com/infinions/analytics:v1.0.0	
    environment:	
      API_PORT: 5600	
      DB_NAME: infin_dev	
      DB_USER: infin	
      DB_PORT: 5432	
      DB_PWD: infin	
      DB_HOST: db	
      DB_ANALYTICS: 'mongodb://analytics_db:27017/'	
      DB_ANALYTICS_HOST: analytics_db	
      DB_ANAKYTICS_PORT: 27017	
    ports:	
    - 5600:5600	

  analytics_db:	
    image: mongo	
    ports:	
    - 27017:27017

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: infin_dev
      POSTGRES_PASSWORD: infin
      POSTGRES_USER: infin
    ports:
    - 5432:5432
