version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: infin_dev
      POSTGRES_PASSWORD: infin
      POSTGRES_USER: infin
    ports:
    - 5432:5432
